#include "PluginEditor.h"
#include "Parameters.h"

// Generated by juce_add_binary_data(NotSureAssets ...).
#include "BinaryData.h"

// ===========================================================================
// Layout, all in the 1792 x 592 design space (see UI-SPEC.md).
// ===========================================================================
namespace layout
{
    struct KnobSpec { const char* id; const char* name; int cx, cy, r; bool darkPointer; };

    // Parameter, name (tooltip only), cap centre, cap radius, dark-pointer flag.
    const KnobSpec knobs[] {
        { ParamID::crush,    "crush",     198, 406, 45, true  }, // white cap: dark groove
        { ParamID::crunch,   "crunch",    434, 408, 45, false },
        { ParamID::sag,      "sag",       667, 408, 45, false },
        { ParamID::darkness, "darkness",  895, 408, 45, false },
        { ParamID::mix,      "mix",      1338, 408, 45, false },
        { ParamID::trim,     "trim",     1584, 406, 45, false },
    };

    // Switch tiles: the union across all positions, 3 px margin already added.
    const juce::Rectangle<int> attackTile   {  639, 271, 78, 54 };
    const juce::Rectangle<int> qualityTile  { 1298, 270, 63, 56 };
    const juce::Rectangle<int> autogainTile { 1545, 270, 59, 60 };

    // Lamp and bypass come from off.png, drawn only when bypassed.
    const juce::Rectangle<int> lampTile   { 1442, 115, 79, 79 };
    const juce::Rectangle<int> bypassTile { 1572, 108, 64, 101 };

    // Click target for the update notice: the red lettering (x737..1052,
    // y99..118) plus a comfortable vertical margin, staying inside the scratched
    // area of newver.png so nothing looks off.
    const juce::Rectangle<int> noticeRect { 732, 87, 326, 44 };

    // Positions.
    enum Position { left = 0, centre = 1, right = 2 };
}

namespace
{
    juce::Rectangle<int> scaled (juce::Rectangle<int> design, float scale)
    {
        return (design.toFloat() * scale).toNearestInt();
    }

    // Transparent hit area over the update-notice lettering: a pointing-hand
    // cursor and a click that runs onClick. The lettering itself is drawn by the
    // editor from the overlay image; this only handles interaction.
    class UpdateLink final : public juce::Component
    {
    public:
        std::function<void()> onClick;

        UpdateLink() { setMouseCursor (juce::MouseCursor::PointingHandCursor); }

        void mouseUp (const juce::MouseEvent& e) override
        {
            if (onClick != nullptr && getLocalBounds().contains (e.getPosition()))
                onClick();
        }
    };
}

// ===========================================================================
// Tile controls.
//
// A tile is a rectangle of the panel that changes with a parameter. Painting a
// state blits that state's sub-rectangle from an overlay image onto the tile;
// the state already baked into main.png draws nothing. Each tile redraws only
// itself, and only when its parameter moves - no timer.
// ===========================================================================
namespace
{
    class TileBase : public juce::Component,
                     public juce::TooltipClient,
                     private juce::AudioProcessorValueTreeState::Listener,
                     private juce::AsyncUpdater
    {
    public:
        TileBase (juce::AudioProcessorValueTreeState& s, juce::String pid,
                  juce::Rectangle<int> designTile, juce::String niceName)
            : apvts (s), paramId (std::move (pid)),
              tile (designTile), name (std::move (niceName))
        {
            apvts.addParameterListener (paramId, this);
        }

        ~TileBase() override { apvts.removeParameterListener (paramId, this); }

        juce::String getTooltip() override
        {
            if (auto* p = apvts.getParameter (paramId))
                return name + ": " + p->getCurrentValueAsText();
            return name;
        }

    protected:
        // Blit the tile's sub-rectangle of img over this whole (scaled) tile.
        // Source coordinates are the design-space rectangle, which equals the
        // pixel rectangle since the artwork is authored at design size.
        void blit (juce::Graphics& g, const juce::Image& img) const
        {
            if (img.isValid())
                g.drawImage (img, 0, 0, getWidth(), getHeight(),
                             tile.getX(), tile.getY(), tile.getWidth(), tile.getHeight());
        }

        int paramIndex() const
        {
            if (auto* p = apvts.getParameter (paramId))
                return (int) std::lround (p->convertFrom0to1 (p->getValue()));
            return 0;
        }

        void setParamIndex (int idx)
        {
            if (auto* p = apvts.getParameter (paramId))
            {
                p->beginChangeGesture();
                p->setValueNotifyingHost (p->convertTo0to1 ((float) idx));
                p->endChangeGesture();
            }
        }

        juce::AudioProcessorValueTreeState& apvts;
        juce::String paramId, name;
        juce::Rectangle<int> tile;

    private:
        void parameterChanged (const juce::String&, float) override { triggerAsyncUpdate(); }
        void handleAsyncUpdate() override { repaint(); }
    };

    // Three-position (attack, quality) or two-position (auto gain) slider.
    //
    // The overlays are sparse: only positions that differ from the one baked
    // into main.png exist. So if the requested position is the baked one, we
    // draw nothing; otherwise we blit from the overlay for that position, which
    // is guaranteed to contain this switch.
    class SwitchControl final : public TileBase
    {
    public:
        SwitchControl (juce::AudioProcessorValueTreeState& s, juce::String pid,
                       juce::Rectangle<int> designTile, int positions, int bakedPos,
                       const juce::Image& left, const juce::Image& centre,
                       const juce::Image& right, juce::String niceName)
            : TileBase (s, std::move (pid), designTile, std::move (niceName)),
              numPositions (positions), bakedPosition (bakedPos),
              overlay { &left, &centre, &right } {}

        void paint (juce::Graphics& g) override
        {
            const int pos = position();
            if (pos != bakedPosition)
                blit (g, *overlay[(size_t) pos]);
        }

        void mouseUp (const juce::MouseEvent&) override
        {
            const int idx = paramIndex();
            setParamIndex (numPositions == 3 ? (idx + 1) % 3 : (1 - idx));
        }

    private:
        // Parameter index -> panel position. Three-position controls map one to
        // one; the two-position auto gain uses left for off and right for on.
        int position() const
        {
            const int idx = paramIndex();
            if (numPositions == 3)
                return idx;
            return idx == 0 ? layout::left : layout::right;
        }

        int numPositions, bakedPosition;
        std::array<const juce::Image*, 3> overlay;
    };

    // Lamp (not clickable) or bypass lever (clickable): both draw their tile
    // from off.png only while the bypass parameter is engaged.
    class BypassTile final : public TileBase
    {
    public:
        BypassTile (juce::AudioProcessorValueTreeState& s, juce::Rectangle<int> designTile,
                    const juce::Image& offImage, bool clickable, juce::String niceName)
            : TileBase (s, ParamID::bypass, designTile, std::move (niceName)),
              img (offImage), interactive (clickable)
        {
            setInterceptsMouseClicks (clickable, clickable);
        }

        void paint (juce::Graphics& g) override
        {
            if (paramIndex() >= 1) // bypassed
                blit (g, img);
        }

        void mouseUp (const juce::MouseEvent&) override
        {
            if (interactive)
                setParamIndex (paramIndex() >= 1 ? 0 : 1);
        }

    private:
        const juce::Image& img;
        bool interactive;
    };
}

// ===========================================================================
// Pointer-only look and feel.
// ===========================================================================
void NotSurePointerLNF::drawRotarySlider (juce::Graphics& g, int x, int y, int w, int h,
                                          float pos, float startAngle, float endAngle,
                                          juce::Slider& slider)
{
    using namespace juce;

    const auto bounds = Rectangle<float> ((float) x, (float) y, (float) w, (float) h);
    const auto cx = bounds.getCentreX();
    const auto cy = bounds.getCentreY();
    const auto r  = jmin (bounds.getWidth(), bounds.getHeight()) * 0.5f;

    const auto a  = startAngle + pos * (endAngle - startAngle);
    const auto dx = std::sin (a);
    const auto dy = -std::cos (a);

    // From near the centre out toward the rim.
    const Point<float> p1 (cx + dx * (r * 0.04f), cy + dy * (r * 0.04f));
    const Point<float> p2 (cx + dx * (r * 0.74f), cy + dy * (r * 0.74f));

    const float thickness = 0.085f * r;

    Path line;
    line.startNewSubPath (p1);
    line.lineTo (p2);
    const PathStrokeType stroke (thickness, PathStrokeType::curved, PathStrokeType::rounded);

    // Shadow: 1 px right, 1.5 px down in design space, scaled with the cap
    // (the design radius is a constant 45, so scale = r / 45).
    const float s = r / 45.0f;
    g.setColour (Colour (0xff1c1610).withAlpha (0.43f));
    g.strokePath (line, stroke, AffineTransform::translation (1.0f * s, 1.5f * s));

    // Dark groove on the white crush cap, off-white incised line on the rest.
    const bool dark = (bool) slider.getProperties().getWithDefault ("darkPointer", false);
    g.setColour (dark ? Colour (0xff60543a).withAlpha (0.88f)
                      : Colour (0xffcec7b4).withAlpha (0.84f));
    g.strokePath (line, stroke);
}

// ===========================================================================
// Editor.
// ===========================================================================
NotSureEditor::NotSureEditor (NotSureProcessor& p)
    : juce::AudioProcessorEditor (&p), processorRef (p)
{
    setOpaque (true);

    main     = juce::ImageCache::getFromMemory (BinaryData::main_png,     BinaryData::main_pngSize);
    off      = juce::ImageCache::getFromMemory (BinaryData::off_png,      BinaryData::off_pngSize);
    allLeft  = juce::ImageCache::getFromMemory (BinaryData::allleft_png,  BinaryData::allleft_pngSize);
    allCentre= juce::ImageCache::getFromMemory (BinaryData::allcenter_png,BinaryData::allcenter_pngSize);
    allRight = juce::ImageCache::getFromMemory (BinaryData::allright_png, BinaryData::allright_pngSize);

    // --- knobs --------------------------------------------------------------
    for (int i = 0; i < numKnobs; ++i)
    {
        const auto& spec = layout::knobs[i];
        knobCapBox[(size_t) i] = { spec.cx - spec.r, spec.cy - spec.r, spec.r * 2, spec.r * 2 };

        auto& k = knobs[(size_t) i];
        k.getProperties().set ("darkPointer", spec.darkPointer);
        k.setSliderStyle (juce::Slider::RotaryHorizontalVerticalDrag);
        k.setRotaryParameters (juce::MathConstants<float>::pi * 1.25f,
                               juce::MathConstants<float>::pi * 2.75f, true);
        k.setTextBoxStyle (juce::Slider::NoTextBox, false, 0, 0);
        k.setColour (juce::Slider::rotarySliderFillColourId,    juce::Colours::transparentBlack);
        k.setColour (juce::Slider::rotarySliderOutlineColourId, juce::Colours::transparentBlack);
        k.setLookAndFeel (&pointerLnf);
        addAndMakeVisible (k);
        knobAtt[(size_t) i] = std::make_unique<SliderAtt> (processorRef.apvts, spec.id, k);

        // Tooltip carries name and live value; the attachment keeps it current
        // on automation too.
        const juce::String name = spec.name;
        k.onValueChange = [this, i, name]
        {
            auto& s = knobs[(size_t) i];
            s.setTooltip (name + ": " + s.getTextFromValue (s.getValue()));
        };
        k.onValueChange();
    }

    knobs[4].setTextValueSuffix (" %");   // mix
    knobs[5].setTextValueSuffix (" dB");  // trim

    // --- switches, lamp, bypass --------------------------------------------
    auto addTile = [this] (std::unique_ptr<juce::Component> c, juce::Rectangle<int> design)
    {
        addAndMakeVisible (*c);
        tiles.push_back ({ std::move (c), design });
    };

    // Baked-in positions in main.png: attack LEFT, quality RIGHT, autogain RIGHT.
    addTile (std::make_unique<SwitchControl> (processorRef.apvts, ParamID::attackMode,
                 layout::attackTile, 3, layout::left, allLeft, allCentre, allRight, "attack"),
             layout::attackTile);

    addTile (std::make_unique<SwitchControl> (processorRef.apvts, ParamID::oversampling,
                 layout::qualityTile, 3, layout::right, allLeft, allCentre, allRight, "quality"),
             layout::qualityTile);

    addTile (std::make_unique<SwitchControl> (processorRef.apvts, ParamID::autoGain,
                 layout::autogainTile, 2, layout::right, allLeft, allCentre, allRight, "auto gain"),
             layout::autogainTile);

    addTile (std::make_unique<BypassTile> (processorRef.apvts, layout::lampTile,
                 off, false, "lamp"),
             layout::lampTile);

    addTile (std::make_unique<BypassTile> (processorRef.apvts, layout::bypassTile,
                 off, true, "bypass"),
             layout::bypassTile);

    // --- update notice ------------------------------------------------------
    newver = juce::ImageCache::getFromMemory (BinaryData::newver_png, BinaryData::newver_pngSize);

    updateLink = std::make_unique<UpdateLink>();
    static_cast<UpdateLink*> (updateLink.get())->onClick = []
    {
        juce::URL (notsure::UpdateChecker::getInstance().getDownloadUrl()).launchInDefaultBrowser();
    };
    addChildComponent (*updateLink);   // hidden until an update is known

    // One shared check per launch, kicked off on the first editor open - never
    // in the processor constructor, so a plugin scan makes no network traffic.
    auto& checker = notsure::UpdateChecker::getInstance();
    checker.addChangeListener (this);
    checker.start (JucePlugin_VersionString);
    refreshUpdateNotice();

    // --- window -------------------------------------------------------------
    constrainer.setFixedAspectRatio ((double) designWidth / (double) designHeight);
    constrainer.setSizeLimits (700, (int) std::round (700.0f * designHeight / designWidth),
                               (int) designWidth, (int) designHeight);
    setConstrainer (&constrainer);
    setResizable (true, true);

    setSize ((int) (designWidth * 0.5f), (int) (designHeight * 0.5f));
}

NotSureEditor::~NotSureEditor()
{
    notsure::UpdateChecker::getInstance().removeChangeListener (this);

    for (auto& k : knobs)
        k.setLookAndFeel (nullptr);
}

void NotSureEditor::changeListenerCallback (juce::ChangeBroadcaster*)
{
    refreshUpdateNotice();
}

void NotSureEditor::refreshUpdateNotice()
{
    const bool available = notsure::UpdateChecker::getInstance().isUpdateAvailable();

    if (updateLink != nullptr)
    {
        updateLink->setVisible (available);
        updateLink->setInterceptsMouseClicks (available, available);
    }

    // Repaint only the notice's rectangle, not the whole editor.
    const float scale = (float) getWidth() / designWidth;
    repaint (scaled (layout::noticeRect, scale));
}

void NotSureEditor::rebuildBackground()
{
    const int w = getWidth();
    const int h = getHeight();
    if (w <= 0 || h <= 0)
        return;

    // The one place the big image is resampled. Never in paint().
    cachedBackground = juce::Image (juce::Image::ARGB, w, h, true);
    juce::Graphics g (cachedBackground);
    g.setImageResamplingQuality (juce::Graphics::highResamplingQuality);

    if (main.isValid())
        g.drawImage (main, 0, 0, w, h, 0, 0, main.getWidth(), main.getHeight());
    else
        g.fillAll (juce::Colour (0xff9a9a98));
}

void NotSureEditor::paint (juce::Graphics& g)
{
    if (cachedBackground.isValid())
        g.drawImageAt (cachedBackground, 0, 0);
    else
        g.fillAll (juce::Colour (0xff9a9a98));

    // The "new version" overlay composites at the same 1792x592 scale as the
    // panel, so no offset maths. Drawn only when an update is known; when there
    // is none the panel looks exactly as it does today.
    if (newver.isValid() && notsure::UpdateChecker::getInstance().isUpdateAvailable())
        g.drawImage (newver, 0, 0, getWidth(), getHeight(),
                     0, 0, newver.getWidth(), newver.getHeight());
}

void NotSureEditor::resized()
{
    const float scale = (float) getWidth() / designWidth;

    for (int i = 0; i < numKnobs; ++i)
        knobs[(size_t) i].setBounds (scaled (knobCapBox[(size_t) i], scale));

    for (auto& t : tiles)
        t.comp->setBounds (scaled (t.design, scale));

    if (updateLink != nullptr)
        updateLink->setBounds (scaled (layout::noticeRect, scale));

    rebuildBackground();
    repaint();
}
